import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'

export const shadcnColorTokens = [
  'background',
  'foreground',
  'card',
  'card-foreground',
  'popover',
  'popover-foreground',
  'primary',
  'primary-foreground',
  'secondary',
  'secondary-foreground',
  'muted',
  'muted-foreground',
  'accent',
  'accent-foreground',
  'destructive',
  'destructive-foreground',
  'border',
  'input',
  'ring',
  'chart-1',
  'chart-2',
  'chart-3',
  'chart-4',
  'chart-5',
  'sidebar',
  'sidebar-foreground',
  'sidebar-primary',
  'sidebar-primary-foreground',
  'sidebar-accent',
  'sidebar-accent-foreground',
  'sidebar-border',
  'sidebar-ring',
]

export const statusColorTokens = [
  'status-success',
  'status-success-foreground',
  'status-success-muted',
  'status-success-border',
  'status-attention',
  'status-attention-foreground',
  'status-attention-muted',
  'status-attention-border',
  'status-danger',
  'status-danger-foreground',
  'status-danger-muted',
  'status-danger-border',
  'status-info',
  'status-info-foreground',
  'status-info-muted',
  'status-info-border',
  'status-pending',
  'status-pending-foreground',
  'status-pending-muted',
  'status-pending-border',
]

export const readinessColorTokens = [
  'readiness-ready',
  'readiness-ready-foreground',
  'readiness-ready-muted',
  'readiness-ready-border',
  'readiness-attention',
  'readiness-attention-foreground',
  'readiness-attention-muted',
  'readiness-attention-border',
  'readiness-blocked',
  'readiness-blocked-foreground',
  'readiness-blocked-muted',
  'readiness-blocked-border',
  'readiness-not-started',
  'readiness-not-started-foreground',
  'readiness-not-started-muted',
  'readiness-not-started-border',
]

export const semanticColorTokens = [
  ...shadcnColorTokens,
  ...statusColorTokens,
  ...readinessColorTokens,
]

export const baseTokenSpecs = [
  { cssName: '--radius', path: ['radius', 'base'] },
  { cssName: '--font-ui', path: ['font', 'ui'] },
  { cssName: '--font-display', path: ['font', 'display'] },
  { cssName: '--font-code', path: ['font', 'code'] },
  { cssName: '--space-unit', path: ['space', 'unit'] },
  { cssName: '--space-control', path: ['space', 'control'] },
  { cssName: '--elevation-card', path: ['shadow', 'card'] },
  { cssName: '--elevation-popover', path: ['shadow', 'popover'] },
  { cssName: '--duration-fast', path: ['motion', 'duration-fast'] },
  { cssName: '--duration-normal', path: ['motion', 'duration-normal'] },
  { cssName: '--ease-standard', path: ['motion', 'ease-standard'] },
]

export const bootstrapAliases = [
  { cssName: '--color-bg', value: 'var(--background)' },
  { cssName: '--color-text', value: 'var(--foreground)' },
  { cssName: '--color-surface', value: 'var(--card)' },
  { cssName: '--color-accent', value: 'var(--primary)' },
  { cssName: '--color-accent-foreground', value: 'var(--primary-foreground)' },
  { cssName: '--radius-control', value: 'var(--radius)' },
]

const themeSpecs = [
  { name: 'light', selectors: [':root', '[data-theme="light"]'] },
  { name: 'dark', selectors: ['.dark', '[data-theme="dark"]'] },
]

const generatedCssComment = '/* Generated by scripts/generate.mjs. Do not edit directly. */'
const generatedTsComment = '// Generated by scripts/generate.mjs. Do not edit directly.'

export const packageRootUrl = new URL('../', import.meta.url)
export const sourceUrl = new URL('src/tokens.source.json', packageRootUrl)
export const cssUrl = new URL('css/tokens.css', packageRootUrl)
export const tsUrl = new URL('src/tokens.generated.ts', packageRootUrl)

export async function readTokenSource() {
  return JSON.parse(await readFile(sourceUrl, 'utf8'))
}

const getPathValue = (source, path) => {
  let current = source

  for (const segment of path) {
    if (typeof current !== 'object' || current === null || !Object.hasOwn(current, segment)) {
      throw new Error(`Missing token path: ${path.join('.')}`)
    }

    current = current[segment]
  }

  return current
}

export const getTokenValue = (source, path) => {
  const token = getPathValue(source, path)

  if (
    typeof token !== 'object' ||
    token === null ||
    !Object.hasOwn(token, '$value') ||
    typeof token.$value !== 'string'
  ) {
    throw new Error(`Token path does not contain a string $value: ${path.join('.')}`)
  }

  return token.$value
}

const renderSelectors = (selectors) => {
  const lines = []

  for (const selector of selectors.slice(0, -1)) {
    lines.push(`${selector},`)
  }

  lines.push(`${selectors.at(-1)} {`)
  return lines.join('\n')
}

const renderThemeBlock = (source, themeSpec) => {
  const lines = [renderSelectors(themeSpec.selectors)]

  for (const tokenName of semanticColorTokens) {
    const value = getTokenValue(source, ['themes', themeSpec.name, 'color', tokenName])
    lines.push(`  --${tokenName}: ${value};`)
  }

  lines.push('')

  for (const baseSpec of baseTokenSpecs) {
    const value = getTokenValue(source, baseSpec.path)
    lines.push(`  ${baseSpec.cssName}: ${value};`)
  }

  lines.push('')

  for (const alias of bootstrapAliases) {
    lines.push(`  ${alias.cssName}: ${alias.value};`)
  }

  lines.push('}')
  return lines.join('\n')
}

export function buildTokensCss(source) {
  const blocks = []

  for (const themeSpec of themeSpecs) {
    blocks.push(renderThemeBlock(source, themeSpec))
  }

  return `${generatedCssComment}\n\n${blocks.join('\n\n')}\n`
}

export function buildTokensTs(source) {
  return `${generatedTsComment}

export const tokens = ${JSON.stringify(source, null, 2)} as const

export const lightTheme = tokens.themes.light
export const darkTheme = tokens.themes.dark
export type Tokens = typeof tokens
export type ThemeName = keyof typeof tokens.themes
export type SemanticColorToken = keyof typeof tokens.themes.light.color
`
}

export async function writeGeneratedFiles() {
  const source = await readTokenSource()

  await Promise.all([
    mkdir(new URL('css/', packageRootUrl), { recursive: true }),
    mkdir(new URL('src/', packageRootUrl), { recursive: true }),
  ])

  await Promise.all([
    writeFile(cssUrl, buildTokensCss(source)),
    writeFile(tsUrl, buildTokensTs(source)),
  ])
}

const isDirectRun = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href

if (isDirectRun) {
  await writeGeneratedFiles()
}
