import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'

export const shadcnColorTokens = [
  'background',
  'foreground',
  'card',
  'card-foreground',
  'popover',
  'popover-foreground',
  'primary',
  'primary-foreground',
  'secondary',
  'secondary-foreground',
  'muted',
  'muted-foreground',
  'accent',
  'accent-foreground',
  'destructive',
  'destructive-foreground',
  'border',
  'input',
  'ring',
  'chart-1',
  'chart-2',
  'chart-3',
  'chart-4',
  'chart-5',
  'sidebar',
  'sidebar-foreground',
  'sidebar-primary',
  'sidebar-primary-foreground',
  'sidebar-accent',
  'sidebar-accent-foreground',
  'sidebar-border',
  'sidebar-ring',
]

export const commandColorTokens = [
  'command',
  'command-foreground',
  'command-muted',
  'command-border',
  'command-accent',
  'command-accent-foreground',
  'command-progress',
  'command-progress-muted',
  'command-segment-investable',
  'command-segment-entry-fees',
  'command-segment-spv-fees',
  'command-segment-neutral',
]

export const statusColorTokens = [
  'status-success',
  'status-success-foreground',
  'status-success-muted',
  'status-success-border',
  'status-attention',
  'status-attention-foreground',
  'status-attention-muted',
  'status-attention-border',
  'status-danger',
  'status-danger-foreground',
  'status-danger-muted',
  'status-danger-border',
  'status-info',
  'status-info-foreground',
  'status-info-muted',
  'status-info-border',
  'status-pending',
  'status-pending-foreground',
  'status-pending-muted',
  'status-pending-border',
]

export const readinessColorTokens = [
  'readiness-ready',
  'readiness-ready-foreground',
  'readiness-ready-muted',
  'readiness-ready-border',
  'readiness-attention',
  'readiness-attention-foreground',
  'readiness-attention-muted',
  'readiness-attention-border',
  'readiness-blocked',
  'readiness-blocked-foreground',
  'readiness-blocked-muted',
  'readiness-blocked-border',
  'readiness-not-started',
  'readiness-not-started-foreground',
  'readiness-not-started-muted',
  'readiness-not-started-border',
]

export const semanticColorTokens = [
  ...shadcnColorTokens,
  ...commandColorTokens,
  ...statusColorTokens,
  ...readinessColorTokens,
]

export const baseTokenSpecs = [
  { cssName: '--radius', path: ['radius', 'base'], type: 'dimension' },
  { cssName: '--font-ui', path: ['font', 'ui'], type: 'fontFamily' },
  { cssName: '--font-display', path: ['font', 'display'], type: 'fontFamily' },
  { cssName: '--font-code', path: ['font', 'code'], type: 'fontFamily' },
  { cssName: '--space-unit', path: ['space', 'unit'], type: 'dimension' },
  { cssName: '--space-control', path: ['space', 'control'], type: 'dimension' },
  { cssName: '--elevation-card', path: ['shadow', 'card'], type: 'shadow' },
  { cssName: '--elevation-popover', path: ['shadow', 'popover'], type: 'shadow' },
  { cssName: '--duration-fast', path: ['motion', 'duration-fast'], type: 'duration' },
  { cssName: '--duration-normal', path: ['motion', 'duration-normal'], type: 'duration' },
  { cssName: '--ease-standard', path: ['motion', 'ease-standard'], type: 'cubicBezier' },
]

export const bootstrapAliases = [
  { cssName: '--color-bg', value: 'var(--background)' },
  { cssName: '--color-text', value: 'var(--foreground)' },
  { cssName: '--color-surface', value: 'var(--card)' },
  { cssName: '--color-accent', value: 'var(--primary)' },
  { cssName: '--color-accent-foreground', value: 'var(--primary-foreground)' },
  { cssName: '--radius-control', value: 'var(--radius)' },
]

const themeSpecs = [
  { name: 'light', selectors: [':root', '[data-theme="light"]'] },
  { name: 'dark', selectors: ['.dark', '[data-theme="dark"]'] },
]

const generatedCssComment = '/* Generated by scripts/generate.mjs. Do not edit directly. */'
const generatedTsComment = '// Generated by scripts/generate.mjs. Do not edit directly.'
const tokenSchemaVersion = 'funding.design-tokens.v1'
const oklchValuePattern =
  /^oklch\(\s*(-?\d*\.?\d+%?)\s+(-?\d*\.?\d+)\s+(-?\d*\.?\d+)(?:deg)?(?:\s*\/\s*[^)]+)?\s*\)$/

export const packageRootUrl = new URL('../', import.meta.url)
export const sourceUrl = new URL('src/tokens.source.json', packageRootUrl)
export const cssUrl = new URL('css/tokens.css', packageRootUrl)
export const tsUrl = new URL('src/tokens.generated.ts', packageRootUrl)

const isRecord = (value) => typeof value === 'object' && value !== null && !Array.isArray(value)

export const validateTokenSourceShape = (source) => {
  const errors = []

  if (!isRecord(source)) {
    return ['Token source must be a JSON object.']
  }

  if (source.$schemaVersion !== tokenSchemaVersion) {
    errors.push(`Token source $schemaVersion must be ${tokenSchemaVersion}.`)
  }

  if (!isRecord(source.meta)) {
    errors.push('Token source meta must be an object.')
  } else {
    validateNonEmptyString(source.meta.name, 'meta.name', errors)
    validateNonEmptyString(source.meta.description, 'meta.description', errors)
  }

  if (!isRecord(source.themes)) {
    errors.push('Token source must contain a themes object.')
  }

  for (const themeName of ['light', 'dark']) {
    const theme = isRecord(source.themes) ? source.themes[themeName] : undefined

    if (!isRecord(theme)) {
      errors.push(`Token source themes.${themeName} must be an object.`)
      continue
    }

    if (!isRecord(theme.color)) {
      errors.push(`Token source themes.${themeName}.color must be an object.`)
      continue
    }

    for (const tokenName of semanticColorTokens) {
      validateSourceToken(
        theme.color[tokenName],
        `themes.${themeName}.color.${tokenName}`,
        errors,
        {
          type: 'color',
          valuePattern: oklchValuePattern,
          valuePatternLabel: 'oklch() color value',
        },
      )
    }
  }

  for (const baseSpec of baseTokenSpecs) {
    validateSourceToken(
      getOptionalPathValue(source, baseSpec.path),
      baseSpec.path.join('.'),
      errors,
      { type: baseSpec.type },
    )
  }

  return errors
}

export const assertValidTokenSourceShape = (source) => {
  const errors = validateTokenSourceShape(source)

  if (errors.length > 0) {
    throw new Error(`Invalid token source shape:\n${errors.join('\n')}`)
  }
}

export async function readTokenSource() {
  const source = JSON.parse(await readFile(sourceUrl, 'utf8'))
  assertValidTokenSourceShape(source)
  return source
}

const getPathValue = (source, path) => {
  let current = source

  for (const segment of path) {
    if (typeof current !== 'object' || current === null || !Object.hasOwn(current, segment)) {
      throw new Error(`Missing token path: ${path.join('.')}`)
    }

    current = current[segment]
  }

  return current
}

const getOptionalPathValue = (source, path) => {
  let current = source

  for (const segment of path) {
    if (!isRecord(current) || !Object.hasOwn(current, segment)) {
      return undefined
    }

    current = current[segment]
  }

  return current
}

const validateNonEmptyString = (value, path, errors) => {
  if (typeof value !== 'string' || value.trim().length === 0) {
    errors.push(`Token source ${path} must be a non-empty string.`)
  }
}

const validateSourceToken = (token, path, errors, options = {}) => {
  if (!isRecord(token)) {
    errors.push(`Token source ${path} must be an object with a string $value.`)
    return
  }

  if (!Object.hasOwn(token, '$value') || typeof token.$value !== 'string') {
    errors.push(`Token source ${path} must contain a string $value.`)
  }

  if (token.$type !== options.type) {
    errors.push(`Token source ${path} $type must be ${options.type}.`)
  }

  if (
    typeof token.$value === 'string' &&
    options.valuePattern !== undefined &&
    !options.valuePattern.test(token.$value)
  ) {
    errors.push(`Token source ${path} $value must be an ${options.valuePatternLabel}.`)
  }
}

export const getTokenValue = (source, path) => {
  const token = getPathValue(source, path)

  if (
    typeof token !== 'object' ||
    token === null ||
    !Object.hasOwn(token, '$value') ||
    typeof token.$value !== 'string'
  ) {
    throw new Error(`Token path does not contain a string $value: ${path.join('.')}`)
  }

  return token.$value
}

const renderSelectors = (selectors) => {
  const lines = []

  for (const selector of selectors.slice(0, -1)) {
    lines.push(`${selector},`)
  }

  lines.push(`${selectors.at(-1)} {`)
  return lines.join('\n')
}

const renderThemeBlock = (source, themeSpec) => {
  const lines = [renderSelectors(themeSpec.selectors)]

  for (const tokenName of semanticColorTokens) {
    const value = getTokenValue(source, ['themes', themeSpec.name, 'color', tokenName])
    lines.push(`  --${tokenName}: ${value};`)
  }

  lines.push('')

  for (const baseSpec of baseTokenSpecs) {
    const value = getTokenValue(source, baseSpec.path)
    lines.push(`  ${baseSpec.cssName}: ${value};`)
  }

  lines.push('')

  for (const alias of bootstrapAliases) {
    lines.push(`  ${alias.cssName}: ${alias.value};`)
  }

  lines.push('}')
  return lines.join('\n')
}

export function buildTokensCss(source) {
  const blocks = []

  for (const themeSpec of themeSpecs) {
    blocks.push(renderThemeBlock(source, themeSpec))
  }

  return `${generatedCssComment}\n\n${blocks.join('\n\n')}\n`
}

export function buildTokensTs(source) {
  return `${generatedTsComment}

export const tokens = ${JSON.stringify(source, null, 2)} as const

export const lightTheme = tokens.themes.light
export const darkTheme = tokens.themes.dark
export type Tokens = typeof tokens
export type ThemeName = keyof typeof tokens.themes
export type SemanticColorToken = keyof typeof tokens.themes.light.color
`
}

export async function writeGeneratedFiles() {
  const source = await readTokenSource()

  await Promise.all([
    mkdir(new URL('css/', packageRootUrl), { recursive: true }),
    mkdir(new URL('src/', packageRootUrl), { recursive: true }),
  ])

  await Promise.all([
    writeFile(cssUrl, buildTokensCss(source)),
    writeFile(tsUrl, buildTokensTs(source)),
  ])
}

const isDirectRun = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href

if (isDirectRun) {
  await writeGeneratedFiles()
}
