import type {
  DealDocumentsEvidenceGroup,
  DealDocumentsEvidenceLabels,
  DealDocumentsEvidenceReadyState,
  DealDocumentsEvidenceState,
} from './deal-documents-evidence'

export const dealDocumentsEvidenceLabels = {
  documentBlockingLabel: 'Closing impact',
  documentDueLabel: 'Due',
  documentLastActivityLabel: 'Last activity',
  documentOwnerLabel: 'Owner',
  documentRelatedInvestorLabel: 'Related investor',
  documentRequirementLabel: 'Requirement',
  documentStatusLabel: 'Status',
  documentVisibilityLabel: 'Visibility',
  groupCountLabel: 'Items',
  groupVisibilityLabel: 'Visibility',
  groupsTitle: 'Evidence groups',
  loadingLabel: 'Loading documents evidence',
  noGroupDocumentsLabel: 'No evidence items in this group.',
  noGroupsLabel: 'No document evidence is ready for display.',
  subtitle: 'Closing evidence across generated documents, investor evidence, and vehicle setup.',
  summaryTitle: 'Evidence summary',
  title: 'Documents',
} as const satisfies DealDocumentsEvidenceLabels

const defaultEvidenceGroups = [
  {
    countLabel: '3 documents',
    description: 'Documents generated for the close and sponsor-side execution package.',
    documents: [
      {
        blockingLabel: 'Cleared for closing',
        blocksClosing: false,
        description: 'Subscription package generated and countersigned for the current close.',
        id: 'subscription-package',
        label: 'Subscription agreement package',
        lastActivityDateTime: '2026-05-16T13:25:00.000Z',
        lastActivityLabel: 'Reviewed 16 May 2026',
        ownerLabel: 'Legal ops',
        requirement: { kind: 'required', label: 'Required' },
        status: { kind: 'approved', label: 'Approved' },
        visibilityLabel: 'Closing binder',
      },
      {
        blockingLabel: 'Blocks closing',
        blocksClosing: true,
        description: 'The bulletin was rejected after a fee schedule mismatch in the appendix.',
        dueDateTime: '2026-05-18T16:00:00.000Z',
        dueLabel: 'Due 18 May 2026',
        id: 'subscription-bulletin',
        label: 'Subscription bulletin appendix',
        lastActivityDateTime: '2026-05-17T08:40:00.000Z',
        lastActivityLabel: 'Rejected 17 May 2026',
        ownerLabel: 'Legal ops',
        requirement: { kind: 'required', label: 'Required' },
        status: { kind: 'rejected', label: 'Rejected' },
        visibilityLabel: 'Protected close room',
      },
      {
        blockingLabel: 'Does not block closing',
        blocksClosing: false,
        description: 'Wire instructions are uploaded for internal treasury review.',
        id: 'wire-instructions',
        label: 'Wire instruction memo',
        lastActivityDateTime: '2026-05-15T10:15:00.000Z',
        lastActivityLabel: 'Uploaded 15 May 2026',
        ownerLabel: 'Fund admin',
        requirement: { kind: 'optional', label: 'Optional' },
        status: { kind: 'uploaded', label: 'Uploaded' },
        visibilityLabel: 'Internal operations',
      },
    ],
    id: 'generated-closing-documents',
    label: 'Generated closing documents',
    visibilityLabel: 'Protected close room',
  },
  {
    countLabel: '4 evidence items',
    description: 'Investor-provided evidence needed for KYC, KYB, and subscription checks.',
    documents: [
      {
        blockingLabel: 'Blocks closing',
        blocksClosing: true,
        description: 'Beneficial ownership declaration is required before countersignature.',
        dueDateTime: '2026-05-18T12:00:00.000Z',
        dueLabel: 'Due 18 May 2026',
        id: 'meridian-ubo-declaration',
        label: 'Meridian UBO declaration',
        lastActivityDateTime: '2026-05-13T09:20:00.000Z',
        lastActivityLabel: 'Requested 13 May 2026',
        ownerLabel: 'Legal ops',
        relatedInvestorLabel: 'Meridian Ventures',
        requirement: { kind: 'required', label: 'Required' },
        status: { kind: 'missing', label: 'Missing' },
        visibilityLabel: 'Investor evidence',
      },
      {
        blockingLabel: 'Blocks closing',
        blocksClosing: true,
        description: 'Source-of-funds packet is uploaded and waiting on compliance review.',
        dueDateTime: '2026-05-19T15:00:00.000Z',
        dueLabel: 'Due 19 May 2026',
        id: 'helix-source-of-funds',
        label: 'Helix source-of-funds packet',
        lastActivityDateTime: '2026-05-17T06:30:00.000Z',
        lastActivityLabel: 'Uploaded 17 May 2026',
        ownerLabel: 'Compliance',
        relatedInvestorLabel: 'Helix Foundation',
        requirement: { kind: 'required', label: 'Required' },
        status: { kind: 'under_review', label: 'Under review' },
        visibilityLabel: 'Investor evidence',
      },
      {
        blockingLabel: 'Blocks closing',
        blocksClosing: true,
        description: 'Proof of address is older than the accepted review window.',
        dueDateTime: '2026-05-20T16:00:00.000Z',
        dueLabel: 'Due 20 May 2026',
        id: 'riverbend-proof-address',
        label: 'Riverbend proof of address',
        lastActivityDateTime: '2026-05-11T08:00:00.000Z',
        lastActivityLabel: 'Expired 11 May 2026',
        ownerLabel: 'Investor relations',
        relatedInvestorLabel: 'Riverbend Capital',
        requirement: { kind: 'required', label: 'Required' },
        status: { kind: 'expired', label: 'Expired' },
        visibilityLabel: 'Investor evidence',
      },
      {
        blockingLabel: 'Cleared for closing',
        blocksClosing: false,
        description: 'Identity evidence is approved and available to the close binder.',
        id: 'alba-identity',
        label: 'Alba identity document',
        lastActivityDateTime: '2026-05-16T09:35:00.000Z',
        lastActivityLabel: 'Approved 16 May 2026',
        ownerLabel: 'Compliance',
        relatedInvestorLabel: 'Alba Partners',
        requirement: { kind: 'required', label: 'Required' },
        status: { kind: 'approved', label: 'Approved' },
        visibilityLabel: 'Investor evidence',
      },
    ],
    id: 'investor-evidence',
    label: 'Investor evidence',
    visibilityLabel: 'Investor-visible data room',
  },
  {
    countLabel: '2 documents',
    description: 'Evidence that the vehicle and target-side setup can support closing.',
    documents: [
      {
        blockingLabel: 'Cleared for closing',
        blocksClosing: false,
        description: 'SPV register extract confirms vehicle setup and administrator review.',
        id: 'spv-register-extract',
        label: 'SPV register extract',
        lastActivityDateTime: '2026-05-14T12:30:00.000Z',
        lastActivityLabel: 'Approved 14 May 2026',
        ownerLabel: 'Fund admin',
        requirement: { kind: 'required', label: 'Required' },
        status: { kind: 'approved', label: 'Approved' },
        visibilityLabel: 'Internal operations',
      },
      {
        blockingLabel: 'Does not block closing',
        blocksClosing: false,
        description: 'Target-side board pack is uploaded for the final data-room snapshot.',
        id: 'target-legal-pack',
        label: 'Target legal pack',
        lastActivityDateTime: '2026-05-15T14:45:00.000Z',
        lastActivityLabel: 'Uploaded 15 May 2026',
        ownerLabel: 'Portfolio ops',
        requirement: { kind: 'optional', label: 'Optional' },
        status: { kind: 'uploaded', label: 'Uploaded' },
        visibilityLabel: 'Protected data room',
      },
    ],
    id: 'vehicle-target-setup',
    label: 'Vehicle and target setup',
    visibilityLabel: 'Internal and protected',
  },
] as const satisfies readonly DealDocumentsEvidenceGroup[]

export const defaultDocumentsEvidenceState = {
  groups: defaultEvidenceGroups,
  kind: 'ready',
} as const satisfies DealDocumentsEvidenceReadyState

export const readyDocumentsEvidenceState = {
  groups: [
    {
      countLabel: '3 documents',
      description: 'All generated close documents are approved for the current closing cohort.',
      documents: [
        {
          blockingLabel: 'Cleared for closing',
          blocksClosing: false,
          id: 'ready-subscription-package',
          label: 'Executed subscription package',
          lastActivityDateTime: '2026-05-17T07:45:00.000Z',
          lastActivityLabel: 'Approved 17 May 2026',
          ownerLabel: 'Legal ops',
          requirement: { kind: 'required', label: 'Required' },
          status: { kind: 'approved', label: 'Approved' },
          visibilityLabel: 'Closing binder',
        },
        {
          blockingLabel: 'Cleared for closing',
          blocksClosing: false,
          id: 'ready-side-letter',
          label: 'Executed side letter',
          lastActivityDateTime: '2026-05-17T07:30:00.000Z',
          lastActivityLabel: 'Approved 17 May 2026',
          ownerLabel: 'Legal ops',
          requirement: { kind: 'required', label: 'Required' },
          status: { kind: 'approved', label: 'Approved' },
          visibilityLabel: 'Protected close room',
        },
        {
          blockingLabel: 'Cleared for closing',
          blocksClosing: false,
          id: 'ready-wire-memo',
          label: 'Final wire instruction memo',
          lastActivityDateTime: '2026-05-16T15:00:00.000Z',
          lastActivityLabel: 'Approved 16 May 2026',
          ownerLabel: 'Fund admin',
          requirement: { kind: 'optional', label: 'Optional' },
          status: { kind: 'approved', label: 'Approved' },
          visibilityLabel: 'Internal operations',
        },
      ],
      id: 'ready-generated-documents',
      label: 'Generated closing documents',
      visibilityLabel: 'Protected close room',
    },
    {
      countLabel: '2 evidence items',
      description: 'Investor evidence is approved and available for close review.',
      documents: [
        {
          blockingLabel: 'Cleared for closing',
          blocksClosing: false,
          id: 'ready-kyb',
          label: 'KYB approval evidence',
          lastActivityDateTime: '2026-05-16T10:10:00.000Z',
          lastActivityLabel: 'Approved 16 May 2026',
          ownerLabel: 'Compliance',
          relatedInvestorLabel: 'Meridian Ventures',
          requirement: { kind: 'required', label: 'Required' },
          status: { kind: 'approved', label: 'Approved' },
          visibilityLabel: 'Investor evidence',
        },
        {
          blockingLabel: 'Cleared for closing',
          blocksClosing: false,
          id: 'ready-source-funds',
          label: 'Source-of-funds approval',
          lastActivityDateTime: '2026-05-16T09:20:00.000Z',
          lastActivityLabel: 'Approved 16 May 2026',
          ownerLabel: 'Compliance',
          relatedInvestorLabel: 'Helix Foundation',
          requirement: { kind: 'required', label: 'Required' },
          status: { kind: 'approved', label: 'Approved' },
          visibilityLabel: 'Investor evidence',
        },
      ],
      id: 'ready-investor-evidence',
      label: 'Investor evidence',
      visibilityLabel: 'Investor-visible data room',
    },
  ],
  kind: 'ready',
} as const satisfies DealDocumentsEvidenceReadyState

export const missingEvidenceState = {
  groups: [
    {
      countLabel: '2 evidence items',
      description: 'Required investor evidence is absent from the closing package.',
      documents: [
        {
          blockingLabel: 'Blocks closing',
          blocksClosing: true,
          description: 'Entity chart is required before KYB can be approved.',
          dueDateTime: '2026-05-18T12:00:00.000Z',
          dueLabel: 'Due 18 May 2026',
          id: 'missing-entity-chart',
          label: 'Meridian entity ownership chart',
          lastActivityDateTime: '2026-05-15T08:05:00.000Z',
          lastActivityLabel: 'Requested 15 May 2026',
          ownerLabel: 'Legal ops',
          relatedInvestorLabel: 'Meridian Ventures',
          requirement: { kind: 'required', label: 'Required' },
          status: { kind: 'missing', label: 'Missing' },
          visibilityLabel: 'Investor evidence',
        },
        {
          blockingLabel: 'Blocks closing',
          blocksClosing: true,
          description: 'Personal identity evidence is missing for the authorized signatory.',
          dueDateTime: '2026-05-18T12:00:00.000Z',
          dueLabel: 'Due 18 May 2026',
          id: 'missing-signatory-id',
          label: 'Authorized signatory identity document',
          lastActivityDateTime: '2026-05-15T08:05:00.000Z',
          lastActivityLabel: 'Requested 15 May 2026',
          ownerLabel: 'Investor relations',
          relatedInvestorLabel: 'Meridian Ventures',
          requirement: { kind: 'required', label: 'Required' },
          status: { kind: 'missing', label: 'Missing' },
          visibilityLabel: 'Investor evidence',
        },
      ],
      id: 'missing-investor-evidence',
      label: 'Investor evidence',
      visibilityLabel: 'Investor-visible data room',
    },
  ],
  kind: 'ready',
} as const satisfies DealDocumentsEvidenceReadyState

export const rejectedExpiredEvidenceState = {
  groups: [
    {
      countLabel: '2 documents',
      description: 'Uploaded documents are present but no longer acceptable for close.',
      documents: [
        {
          blockingLabel: 'Blocks closing',
          blocksClosing: true,
          description: 'Rejected because the investor legal name does not match the subscription.',
          dueDateTime: '2026-05-18T16:00:00.000Z',
          dueLabel: 'Due 18 May 2026',
          id: 'rejected-side-letter',
          label: 'Investor side letter',
          lastActivityDateTime: '2026-05-17T08:40:00.000Z',
          lastActivityLabel: 'Rejected 17 May 2026',
          ownerLabel: 'Legal ops',
          relatedInvestorLabel: 'Riverbend Capital',
          requirement: { kind: 'required', label: 'Required' },
          status: { kind: 'rejected', label: 'Rejected' },
          visibilityLabel: 'Protected close room',
        },
        {
          blockingLabel: 'Blocks closing',
          blocksClosing: true,
          description: 'Address evidence expired before the scheduled close date.',
          dueDateTime: '2026-05-19T16:00:00.000Z',
          dueLabel: 'Due 19 May 2026',
          id: 'expired-address-evidence',
          label: 'Proof of address',
          lastActivityDateTime: '2026-05-11T08:00:00.000Z',
          lastActivityLabel: 'Expired 11 May 2026',
          ownerLabel: 'Compliance',
          relatedInvestorLabel: 'Alba Partners',
          requirement: { kind: 'required', label: 'Required' },
          status: { kind: 'expired', label: 'Expired' },
          visibilityLabel: 'Investor evidence',
        },
      ],
      id: 'rejected-expired-evidence',
      label: 'Rejected and expired evidence',
      visibilityLabel: 'Protected and investor evidence',
    },
  ],
  kind: 'ready',
} as const satisfies DealDocumentsEvidenceReadyState

export const underReviewEvidenceState = {
  groups: [
    {
      countLabel: '3 evidence items',
      description: 'Evidence is uploaded and waiting on the named operator review queue.',
      documents: [
        {
          blockingLabel: 'Blocks closing',
          blocksClosing: true,
          description: 'Compliance review is open for the beneficial ownership packet.',
          dueDateTime: '2026-05-19T15:00:00.000Z',
          dueLabel: 'Due 19 May 2026',
          id: 'review-beneficial-ownership',
          label: 'Beneficial ownership packet',
          lastActivityDateTime: '2026-05-17T06:30:00.000Z',
          lastActivityLabel: 'Uploaded 17 May 2026',
          ownerLabel: 'Compliance',
          relatedInvestorLabel: 'Helix Foundation',
          requirement: { kind: 'required', label: 'Required' },
          status: { kind: 'under_review', label: 'Under review' },
          visibilityLabel: 'Investor evidence',
        },
        {
          blockingLabel: 'Does not block closing',
          blocksClosing: false,
          description: 'Optional ESG questionnaire is available for portfolio ops review.',
          id: 'review-esg-questionnaire',
          label: 'ESG questionnaire',
          lastActivityDateTime: '2026-05-16T12:45:00.000Z',
          lastActivityLabel: 'Uploaded 16 May 2026',
          ownerLabel: 'Portfolio ops',
          relatedInvestorLabel: 'Helix Foundation',
          requirement: { kind: 'optional', label: 'Optional' },
          status: { kind: 'under_review', label: 'Under review' },
          visibilityLabel: 'Investor evidence',
        },
        {
          blockingLabel: 'Does not block closing',
          blocksClosing: false,
          description: 'Sponsor memo is uploaded and waiting on internal acknowledgment.',
          id: 'review-sponsor-memo',
          label: 'Sponsor close memo',
          lastActivityDateTime: '2026-05-16T11:15:00.000Z',
          lastActivityLabel: 'Uploaded 16 May 2026',
          ownerLabel: 'Legal ops',
          requirement: { kind: 'optional', label: 'Optional' },
          status: { kind: 'under_review', label: 'Under review' },
          visibilityLabel: 'Internal operations',
        },
      ],
      id: 'under-review-evidence',
      label: 'Under review',
      visibilityLabel: 'Mixed visibility',
    },
  ],
  kind: 'ready',
} as const satisfies DealDocumentsEvidenceReadyState

export const noDocumentsEvidenceState = {
  groups: [],
  kind: 'ready',
} as const satisfies DealDocumentsEvidenceReadyState

export const longTextDocumentsEvidenceState = {
  groups: [
    {
      countLabel: '1 evidence item with unusually long text',
      description:
        'Cross-border evidence that must retain full legal names, long responsible-team labels, and a dense explanation without truncating important review context.',
      documents: [
        {
          blockingLabel:
            'Blocks closing until legal, compliance, fund administration, and investor relations agree that the evidence can be relied on for the final close',
          blocksClosing: true,
          description:
            'The investor supplied a consolidated ownership memo with multiple jurisdictions, translated appendices, and sponsor-side notes that need to remain readable inside a constrained operator workspace.',
          dueDateTime: '2026-05-20T16:00:00.000Z',
          dueLabel: 'Due 20 May 2026 at 18:00 Europe/Paris',
          id: 'long-cross-border-ownership-evidence',
          label:
            'Cross-border beneficial ownership memorandum with translated appendices and sponsor review notes',
          lastActivityDateTime: '2026-05-17T15:25:00.000Z',
          lastActivityLabel:
            'Updated 17 May 2026 after compliance attached the translated registry extract',
          ownerLabel: 'Legal operations and external counsel review desk',
          relatedInvestorLabel:
            'Northern Meridian Strategic Co-Investment Vehicle II Luxembourg SCSp',
          requirement: { kind: 'required', label: 'Required before close' },
          status: { kind: 'under_review', label: 'Under review' },
          visibilityLabel: 'Protected close room and restricted investor evidence workspace',
        },
      ],
      id: 'long-text-group',
      label: 'Cross-border investor evidence with long labels',
      visibilityLabel: 'Restricted protected data room',
    },
  ],
  kind: 'ready',
} as const satisfies DealDocumentsEvidenceReadyState

export const loadingDocumentsEvidenceState = {
  kind: 'loading',
} as const satisfies DealDocumentsEvidenceState

export const errorDocumentsEvidenceState = {
  description: 'Refresh the evidence workspace and try again.',
  kind: 'error',
  retryLabel: 'Retry',
  title: 'Documents evidence could not be loaded',
} as const satisfies DealDocumentsEvidenceState

export const emptyDocumentsEvidenceState = {
  description: 'Document readiness will appear after the close has evidence requirements.',
  kind: 'empty',
  title: 'No document evidence yet',
} as const satisfies DealDocumentsEvidenceState
