export {
  type DealProgressAction,
  type DealProgressActionAudience,
  type DealProgressActionEvent,
  type DealProgressActionKind,
  type DealProgressActions,
  type DealProgressCapitalSummary,
  type DealProgressDataQuality,
  type DealProgressMetric,
  type DealProgressMetricTone,
  type DealProgressMode,
  DealProgressPanel,
  type DealProgressPanelLabels,
  type DealProgressPanelProps,
  type DealProgressPanelState,
  type DealProgressSegment,
  type DealProgressSegmentKind,
  type DealProgressSegmentTone,
  type DealProgressStage,
  type DealProgressStatus,
  type DealProgressVisibility,
  type DealProgressVisualProgress,
} from './deal-progress-panel'
